package clement.guillaume.sbv_to_ttaf.test;

import java.io.IOException;

import clement.guillaume.sbv_to_ttaf.SbvToTtaf;
import junit.framework.TestCase;

/**
 * The class <code>SbvToTtafTest</code> contains tests for the class {@link
 * <code>SbvToTtaf</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 03/06/16 8:22 AM
 *
 * @author Guillaume Clement
 *
 * @version $Revision$
 */
public class SbvToTtafTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public SbvToTtafTest(String name) {
		super(name);
	}

	/**
	 * Run the void main(String[]) method test
	 * @throws IOException 
	 */
	public void testMain() throws IOException {
	
		// add test code here
		String[] args = {"src/test/resources/captions.sbv","src/test/resources/captions.ttaf"};
		SbvToTtaf.main(args);
		assertTrue(true);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = true
 * createTestStubs = false
 * methods = main([QString;)
 * package = clement.guillaume.sbv_to_ttaf.test
 * package.sourceFolder = sbv-to-ttaf/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = MainTest
 * testClassType = clement.guillaume.sbv_to_ttaf.Main
 */